examples/demo_mearec_extractors.ipynb
examples/demo_spikeinterface_biocam.ipynb
examples/getting_started_with_recording_extractors.ipynb
examples/getting_started_with_sorting_extractors.ipynb
examples/test_spikeinterface_biocam.ipynb
setup.py
spikeinterface/MultiRecordingExtractor.py
spikeinterface/MultiSortingExtractor.py
spikeinterface/RecordingExtractor.py
spikeinterface/SortingExtractor.py
spikeinterface/SubRecordingExtractor.py
spikeinterface/SubSortingExtractor.py
spikeinterface/__init__.py
spikeinterface/extractors/biocaminputextractor/__init__.py
spikeinterface/extractors/biocamrecordingextractor/__init__.py
spikeinterface/extractors/biocamrecordingextractor/biocamrecordingextractor.py
spikeinterface/extractors/hs2outputextractor/__init__.py
spikeinterface/extractors/hs2sortingextractor/__init__.py
spikeinterface/extractors/hs2sortingextractor/hs2sortingextractor.py
spikeinterface/extractors/mdaextractors/__init__.py
spikeinterface/extractors/mdaextractors/mdaextractors.py
spikeinterface/extractors/mearecextractors/__init__.py
spikeinterface/extractors/mearecextractors/mearecextractors.py
spikeinterface/extractors/numpyextractors/__init__.py
spikeinterface/extractors/numpyextractors/numpyextractors.py
tests/test_mda_extractors.py
tests/test_mearec_extractors.py
tests/test_numpy_extractors.py

* = Controversial and worth evaluating
Module: InputExtractor 
- InputExtractor --> RecordingExtractor
- *getEpochNames throws a not implemented error rather than returning an empty list
- *writeInput --> writeRecordedData
- getRawTraces --> getTraces
- getRawSnippets --> getSnippets
Module: SubInputExtractor
- SubInputExtractor --> SubRecordingExtractor
Module: MultiInputExtractor
- MultiInputExtractor --> MultiRecordingExtractor
- import spikeinterface as si --> from .RecordingExtractor import RecordingExtractor
- input_extractors --> recording_extractors
Module: OutputExtractor
- OutputExtractor  --> SortingExtractor
- *writeOutput --> writeSortedData
Module:SubOutputExtractor
- Made SubSortingExtractor a SortingExtractor object rather than an ABC object.
- *total_recording_frames …

Changed everything to Recording and Sorting nomenclature

---

spikeinterface/SortingExtractor.py
spikeinterface/extractors/hs2sortingextractor/hs2sortingextractor.py
spikeinterface/extractors/numpyextractors/numpyextractors.py
tests/test_extractors.py

Purpose of this functionality is to retrieve information about sorted units, such as spike or unit locations.
The interface is based on dictionary keys, and information is stored in a dictionary within each class.
Added functionality to  read info to the HS2 sorting extractor, and to both write and read to the numpy class.
From the HS2 extractor, one can now obtain unit locations ``HS2e.getUnitProperty(u,'unit_location')`` and ``HS2e.getUnitProperty(u,'spike_locations')``
The numpy extractor also allows writing this info, e.g. ``NPe.setUnitProperty('a_new_property', data)``.
I'm neither sure about this implementation, nor about the naming, open for suggestions.

Added getUnitProperty to the sorting extractor.

---

examples/getting_started_with_sorting_extractors.ipynb
spikeinterface/extractors/mdaextractors/mdaextractors.py
spikeinterface/extractors/mearecextractors/mearecextractors.py
spikeinterface/extractors/numpyextractors/numpyextractors.py
tests/test_extractors.py
tests/test_numpy_extractors.py

Adjusted all extractors and tests to return integers in the spike trains. All algorithms that have times go through this procedure:
np.rint(times).astype(int).
If this is desired, we can merge this with master since all the tests pass.

All spike trains returned as integers. Tests adjusted to look for this

---

spikeinterface/MultiRecordingExtractor.py
spikeinterface/RecordingExtractor.py
spikeinterface/SortingExtractor.py
spikeinterface/SubRecordingExtractor.py
spikeinterface/extractors/biocamrecordingextractor/biocamrecordingextractor.py
spikeinterface/extractors/mdaextractors/mdaextractors.py
spikeinterface/extractors/mearecextractors/mearecextractors.py
spikeinterface/extractors/numpyextractors/numpyextractors.py
spikeinterface/extractors/nwbextractors/nwbextractors.py
spikeinterface/extractors/openephysextractors/openephysextractors.py
spikeinterface/tools.py
tests/test_tools.py

- added `getChannelIds()`: if `self._channel_ids` is None, it returns `list(range(num_channels))`, otherwise it returns the list of channel_ids. Channels are handled as units in the SortingExtractors. The only way to change the channel ids is creating a `SubRecordingExtractor` with the `channel_ids` argument.
- updated `loadProbeFile()`:
- returns a subrecording extractor
- if 'channels' is in the probe file, it is considered the channel map
- other properties can be loaded either by passing a dictionary channel_id: property, or a list with the length of the number of channels in the channel group
- when loading locations from csv file, one can pass the `channel_map` and  `channel_group` arguments to load map and group information
- fixed some minor thing in Recording and Sorting …

Added getChannelIds and updated probe file handling

---

spikeinterface/MultiRecordingExtractor.py
spikeinterface/RecordingExtractor.py
spikeinterface/SubRecordingExtractor.py
spikeinterface/extractors/biocamrecordingextractor/biocamrecordingextractor.py
spikeinterface/extractors/mdaextractors/mdaextractors.py
spikeinterface/extractors/mearecextractors/mearecextractors.py
spikeinterface/extractors/numpyextractors/numpyextractors.py
spikeinterface/extractors/nwbextractors/nwbextractors.py
spikeinterface/extractors/openephysextractors/openephysextractors.py
tests/test_extractors.py
tests/test_numpy_extractors.py

All other functions in SpikeInterface have channel_ids (or unit_id) as the first argument in the signature except the getTraces function. I changed all getTraces functions in the tests, extractors, and parent classes including the multi and sub extractors.
Original:
```
def getTraces(self, start_frame=None, end_frame=None, channel_ids=None)
```
Proposed change
```
def getTraces(self, channel_ids=None, start_frame=None, end_frame=None)
```
Other examples
```
def getUnitSpikeTrain(self, unit_id, start_frame=None, end_frame=None):
def setChannelProperty(self, channel_id, property_name, value):
```

Changed getTraces signature to match with the rest of SpikeInterface

---

spikeextractors/tools.py
tests/test_tools.py

* dtype=None by default
* chunksize copy when chunksize is not None
This is about theses problems:
#103 #104 
https://github.com/SpikeInterface/spiketoolkit/issues/72

Improve writeBinaryDatFormat:

---

README.md
examples/getting_started_with_curation.ipynb
examples/getting_started_with_sorting_extractors.ipynb
setup.py
spikeextractors/RecordingExtractor.py
spikeextractors/SortingExtractor.py
spikeextractors/example_datasets/toy_example.py
spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py
spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py
spikeextractors/extractors/exdirextractors/exdirextractors.py
spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py
spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py
spikeextractors/extractors/klustasortingextractor/klustasortingextractor.py
spikeextractors/extractors/mdaextractors/mdaextractors.py
spikeextractors/extractors/mearecextractors/mearecextractors.py
spikeextractors/extractors/numpyextractors/numpyextractors.py
spikeextractors/extractors/openephysextractors/openephysextractors.py
spikeextractors/extractors/physortingextractor/physortingextractor.py
spikeextractors/extractors/spykingcircussortingextractor/spykingcircussortingextractor.py
spikeextractors/extractors/tridesclousextractor/tridesclousextractor.py
tests/test_extractors.py
tests/test_numpy_extractors.py

@samuelgarcia I am changing the type information in the params and moving away from PyQtGraph types which can only be 'str', 'bool', etc. 
The reasons are as follows:
1. There is an annoying bug for PyQtGraph default values (hasDefault always returns True)
2. I want to include more interesting types like 'list' and 'np.dtype' and 'RecordingExtractor' so I think it is best if we have our own parameter reader. It doesn't need to be as complex as PyQtGraph, but it should handle lists and other types more seamlessly.

Changed the type information to be more informative. 

---

spikeextractors/extractors/phyextractors/phyextractors.py

I had to change the name one of the metadata that we use, `ch_group`, to `chan_grp` as the keyword `group` is used for cluster quality

changed ch_group to chan_grp as group is a phy keyword

---

spikeextractors/extraction_tools.py
spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py

If the BinDat extractor is initialized with uint dtype, it might cause errors for some sorters.
This converts uint to int and optionally applies a gain to convert to uV

convert unsigned to signed when returning bindat traces + gain arg

---

spikeextractors/extractors/klustaextractors/klustaextractors.py
spikeextractors/extractors/mearecextractors/mearecextractors.py

- if channel_ids is not ordered in MEArecRecordingExtractor it throws an Error. Patched it
- if running klusta without grouping property but the group information is available, klusta still runs split by group and the unit_ids must be reset to have unique ids

Fixes to h5 order in MEArec and KlustaExtractor

---

spikeextractors/MultiSortingExtractor.py
tests/test_extractors.py

Adding new unit properties and getting unit property names were broken in the multisortingextractor (I had to override the original functions in the class).

Fixed property handling in multisortingextractor

---

spikeextractors/extractors/mearecextractors/mearecextractors.py
tests/test_extractors.py

Update to new h5 backend.
The recgen object need to be a member variable otherwise the underlying h5 file gets closed by the destructor

Updated mearec for h5 destructor

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

'source' args were removed from NWB just prior to the 2.0 release

rmv source from NWB interfaces

---

spikeextractors/__init__.py
spikeextractors/extraction_tools.py
spikeextractors/extractorlist.py
spikeextractors/recordingextractor.py
spikeextractors/sortingextractor.py
tests/test_tools.py

Based off the meeting we had, I implemented extraction tools that are _internal_ to the RecordingExtractor and Sorting Extractor. Now you can call load_probe_file, save_to_probe_file, write_to_binary_dat_format, get_sub_extractors_by_property with:
```
recording.load_probe_file
recording.save_to_probe_file
recording.write_to_binary_dat_format
recording.get_sub_extractors_by_property
```
You can also call:
```
sorting.get_sub_extractors_by_property
```
I left the original functions in extraction_tools and the extractors call those original function internally. I added tests for them and they pass.
I changed two names as well:
save_probe_file --> save_to_probe_file
write_binary_dat_format --> write_to_binary_dat_format

added internal extraction tools

---

.travis.yml
spikeextractors/extractorlist.py
spikeextractors/extractors/nixiorecordingextractor/__init__.py
spikeextractors/extractors/nixiorecordingextractor/nixiorecordingextractor.py
tests/test_extractors.py

This PR adds the NIXIORecordingExtractor for writing to and reading from NIX files using [NIXPy](https://github.com/G-Node/nixpy).  Initial discussion about including NIX can be found in [this issue](https://github.com/G-Node/nixpy/issues/413).
This is an initial attempt based on the contribution guide, the API docs, and the test (adapted from the other RecordingExtractor tests as discussed in the issue linked above).  If it looks like the writer or reader are doing anything out of the ordinary of unexpected, let me know, since I'm not very familiar with SpikeInterface in general.
- The `get_traces()` method is a little strange looking and inefficient.  The indexing in NIXPy isn't very flexible in the latest stable release (1.4.9).  The current beta (1.5.0b3) allows fancy indexing like in …

New recording extractor for nixio (nixpy)

---

spikeextractors/extractors/npzsortingextractor/npzsortingextractor.py
spikeextractors/extractors/spykingcircusextractors/spykingcircusextractors.py

- spykingcircus loaded spiketrains in uint32, causing problems in downstream comparisons
- also force int64 to NPZ

Force spike trains to be int64

---

spikeextractors/extractors/nixiorecordingextractor/nixiorecordingextractor.py

This PR adds support for saving channel properties to NIX files and loading them back on read.
The save function creates a metadata section to store channel properties from a RecordingExtractor and attaches the metadata Section to the traces DataArray.
The writer checks the file format version of the NIX library since it will soon change (with the release of 1.5) and the creation of properties will be simplified.
On `__init__` of the RecordingExtractor, the properties are loaded (handled by the `_load_properties()` method).

[nixio] Save and load properties

---

spikeextractors/extractorlist.py
spikeextractors/extractors/nixioextractors/__init__.py
spikeextractors/extractors/nixioextractors/nixioextractors.py
spikeextractors/extractors/nixiorecordingextractor/__init__.py
tests/test_extractors.py

This PR adds the NIXIOSortingExtractor for writing sorted spikes to and reading from NIX files.  The file and module have been renamed from `nixiorecordingextractor` to `nixioextractors` since they now contain both kinds of extractors.
I also added support for writing and reading unit properties, just like with the NIXIORecordingExtractor.

New sorting extractor for nixio

---

spikeextractors/extractors/exdirextractors/exdirextractors.py

This fixes a bug in the ExdirSortingExtractor.write_sorting().
If groups are available and units are found only in one group, it saves in the proper channel folder.

When single group make sure group id is not 0

---

spikeextractors/extraction_tools.py
spikeextractors/recordingextractor.py
tests/test_tools.py

This is to enforce writing of groups only when selected by the user (especially for spike sorting)
- added `grouping_property`
- removed `format` and added `graph`, `geometry`

Refractor save_to_probe_file

---

spikeextractors/recordingextractor.py

The `get_dtype` function passes now a list of one channel. This should solve several downstream problems as `channel_ids` is often assumed to be a list.

Fix get_dtype

---

spikeextractors/extractors/kilosortextractors/kilosortextractors.py

The `keep_good_only` param should be False by default. It's much easier to filter good units after than the opposite, since they are saved as `KSLabel` property. One can simply do:
```
good_units = []
for u in sort_ks.get_unit_ids():
if sort_ks.get_unit_property(u, 'KSLabel') == 'good':
good_units.append(u)
sort_good = se.SubSortingExtractor(sort_ks, unit_ids=good_units)
```

keep_good_only False by default

---

.travis.yml
spikeextractors/extractors/nwbextractors/nwbextractors.py
spikeextractors/sortingextractor.py
tests/test_extractors.py

This refactor contains some changes that help us integrate NwbRecordingExtractor better with many of our current projects, plus some fixes:
- add metadata control to NwbExtractor. This allows the use of metadata file instructions for NWB file contruction, a practice we’ve been trying to promote. It is optional and the standard conversions recording <--> nwb should work just the same without it.
- breaks down the nwb file formatting code into smaller, nwb-class-specific static methods, which allows us to interact better with each step of the way if needed for more advanced cases. Again, it won’t alter the standard conversions recording <--> nwb.
- fix #320
- fix temporarily #323

Nwb refactor metadata

---

spikeextractors/extraction_tools.py
spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py
spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py
spikeextractors/extractors/exdirextractors/exdirextractors.py
spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py
spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py
spikeextractors/extractors/mcsh5recordingextractor/mcsh5recordingextractor.py
spikeextractors/extractors/mdaextractors/mdaextractors.py
spikeextractors/extractors/mea1krecordingextractor/mea1krecordingextractor.py
spikeextractors/extractors/mearecextractors/mearecextractors.py
spikeextractors/extractors/neoextractors/neobaseextractor.py
spikeextractors/extractors/nixioextractors/nixioextractors.py
spikeextractors/extractors/numpyextractors/numpyextractors.py
spikeextractors/extractors/nwbextractors/nwbextractors.py
spikeextractors/extractors/openephysextractors/openephysextractors.py
spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
spikeextractors/extractors/tridescloussortingextractor/tridescloussortingextractor.py
spikeextractors/multirecordingchannelextractor.py
spikeextractors/multirecordingtimeextractor.py
spikeextractors/recordingextractor.py
spikeextractors/subrecordingextractor.py

@colehurwitz already added some checks for parsing start and end frame.
I suggest a decorator in the extractor tools that:
- checks `start_frame` and `end_frame`
- checks that all `channel_ids` are correct / filters out wrong ones
- parses to `start_frame` and `end_frame` 
Note that this can be accessed by `spiketoolkit` and could be extended in the future. It would cleanup a lot of the code and fix unwanted bugs (e.g. passing `start_frame` < 0 was not caught before o it needed to be done in each get_traces). 
The `@wraps` decorator makes sure that the docstrings is kept.
If you give me the green light I'll do some cleanup :)

Proposal: get_traces decorator

---

spikeextractors/baseextractor.py
spikeextractors/cacherecordingextractor.py
spikeextractors/example_datasets/toy_example.py
spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
spikeextractors/version.py

This makes it easy to know if a RecordingExtractor is filtered or not (especially for spiketoolkit)

Add `is_filtered` to BaseExtractor

---

spikeextractors/cacherecordingextractor.py
spikeextractors/extraction_tools.py
spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py
spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py
spikeextractors/extractors/mea1krecordingextractor/mea1krecordingextractor.py

- found a bad bug in the `read_binary` function, was affecting performance A LOT. Basically, the memmap file was open and closed within the function...
- fixed some indexing in MAxOne and Mea1k extractors
- Cache creates folder if non-existing

Fixes to bindat, maxone, mea1k extractors

---

spikeextractors/extraction_tools.py
spikeextractors/extractors/exdirextractors/exdirextractors.py
spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py
spikeextractors/extractors/klustaextractors/klustaextractors.py
spikeextractors/extractors/mdaextractors/mdaextractors.py
spikeextractors/extractors/mearecextractors/mearecextractors.py
spikeextractors/extractors/neoextractors/neobaseextractor.py
spikeextractors/extractors/neuroscopesortingextractor/neuroscopesortingextractor.py
spikeextractors/extractors/nixioextractors/nixioextractors.py
spikeextractors/extractors/npzsortingextractor/npzsortingextractor.py
spikeextractors/extractors/numpyextractors/numpyextractors.py
spikeextractors/extractors/nwbextractors/nwbextractors.py
spikeextractors/extractors/openephysextractors/openephysextractors.py
spikeextractors/extractors/phyextractors/phyextractors.py
spikeextractors/extractors/shybridextractors/shybridextractors.py
spikeextractors/extractors/spykingcircusextractors/spykingcircusextractors.py
spikeextractors/extractors/tridescloussortingextractor/tridescloussortingextractor.py
spikeextractors/multisortingextractor.py
spikeextractors/subsortingextractor.py

Invalid unit_ids was throwing a key_error that was hard to understand. 
I made a decorator for all the `get_unit_spike_train` functions so that they check the validity of the unit_id beforehand (similar to the get_traces decorator that @alejoe91 made, but less complex).

new decorator for checking unit id validity

---

spikeextractors/baseextractor.py
spikeextractors/cacherecordingextractor.py
spikeextractors/example_datasets/__init__.py
spikeextractors/example_datasets/toy_example.py
spikeextractors/extraction_tools.py
spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py
spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py
spikeextractors/extractors/exdirextractors/exdirextractors.py
spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py
spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py
spikeextractors/extractors/mdaextractors/mdaextractors.py
spikeextractors/extractors/mea1krecordingextractor/mea1krecordingextractor.py
spikeextractors/extractors/mearecextractors/mearecextractors.py
spikeextractors/extractors/numpyextractors/numpyextractors.py
spikeextractors/extractors/nwbextractors/nwbextractors.py
spikeextractors/extractors/phyextractors/phyextractors.py
spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
spikeextractors/multirecordingchannelextractor.py
spikeextractors/recordingextractor.py
spikeextractors/sortingextractor.py
spikeextractors/tests/test_extractors.py
spikeextractors/tests/test_numpy_extractors.py
spikeextractors/tests/test_tools.py
spikeextractors/tests/utils.py

Final dumps! I think this is super important to save the status of recording and sortings (e.g. after extracting waveforms, pca, etc...)
- Added the consept of `key_properties` that for RecordingExtractors are `group` and `location`
- This cleans up property and feature handling, now done at the base class (`self._properties` and `self._features`).
- `make_serialized_dict()` allows saves `key_properties` by default
- 3 dump functions: `dump_to_dict`, `dump_to_json` (both save key properties) and `dump_to_pickle`, that enable saving all features and properties
- The `load_extractor_from_dict` and `load_extractor_from_json` have been modified to load the properties and features and the `load_extractor_from_pickle` has been added

Refractor properties and features for dumping

---

spikeextractors/recordingextractor.py

For a variety of reasons, one of which is that it is typical with python3 to arrive
to `__del__` whenever other attributes were freed already.  It is a bigger issue I am
not going to solve here, rather just to prevent a non interformative crash

BF: do not assume in __del__ that ._tmp_folder is available

---

spikeextractors/baseextractor.py
spikeextractors/exceptions.py
spikeextractors/recordingextractor.py
spikeextractors/sortingextractor.py

- avoid if/elif matching based on the class name (which might
not even have those terms) and would rely on class inheritance to decide
on default filename.
- avoid code duplication by concentrating it in _get_file_path which would
do all necessary steps uniformly regardless or which them method invokes it.
- raises a dedicated NotDumpableExtractorError now instead of too generic
Exception if for some reason current instance is not dumpable.
An alternative to #370 .  Completely alternatively, may be dumping to some default filename should be completely refactored out - IMHO better be explicit than implicit ;) (Zen of Python IIRC)
TODOs:
I have not approached the test since forgot good basic `unittest` with too much of the nose and pytest.  I see that pytest is used as a running on travis …

RF+BF: centralize logic for handling dumping extractors into files

---

spikeextractors/extraction_tools.py
spikeextractors/extractors/nwbextractors/nwbextractors.py
spikeextractors/recordingextractor.py
spikeextractors/tests/test_extractors.py
spikeextractors/tests/test_tools.py

@alejoe91 I really think we should not be returning different types (int or list) for any function. I just caught a bug in SpikeInterface where it was expecting a list and got an int. We always will need `if` statements everywhere if we do this to deal with ints or lists. We removed this in epochs as well.

remove multiple return type

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

Is there a reason that nwb files were opened using 'a' (append) mode? It's causing a problem for me because it updates the create time of the file every time it is opened.

use read mode when opening nwb file

---

spikeextractors/extractors/waveclussortingextractor/waveclussortingextractor.py

I just realized that to write down the sorting results, the units should be integers.

fix wc get_unit_ids

---

spikeextractors/extractors/mdaextractors/mdaextractors.py

I had to change the function to read the geometry file. 
A few lines after loading the file the number of channels on the recording is compared to self._geom.shape[0], but np.genfromtxt read a single line file as a vector of shape [2,] then it looks like the geom describes a 2 channel recording. 
The documentations say that loadtxt is equivalent to genfromtxt.

fix read geom file for single channel

---

spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py
spikeextractors/tests/utils.py

In channel ids are note given, memmap is returned.

Speed up retrieval for bindat when channel ids are not given

---

spikeextractors/extractors/tridescloussortingextractor/tridescloussortingextractor.py

This should fix this:
https://github.com/SpikeInterface/spikesorters/issues/163

Preload all spike once. This avoid memmap lock on the folde.

---

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py

Discovered some new special cases for noisy .res and .clu files in a common directory with the files we actually want to extract from. Also greater enforcement of PEP8 and Numpy docstrings.

Neuroscope clu suffix bug fix

---

spikeextractors/baseextractor.py

This should fix the Windows `PermissionError` problem when attemting to remove the tmp folder (https://github.com/SpikeInterface/spiketoolkit/issues/391)

Delete all memmap objects before removing tmpdir

---

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py
spikeextractors/extractors/nwbextractors/nwbextractors.py

Ran into a somewhat rare issue where more than two-digits (>9) worth of shanks are used. Pretty easy fix, though.

quick fix for detecting higher value .res.%i and .res.%i ids

---

spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py
spikeextractors/extractors/mea1krecordingextractor/mea1krecordingextractor.py
spikeextractors/multirecordingchannelextractor.py

- fix channel locations (only for routed electrodes)
- load spike rates as `activity` property
- implement `get_electrode_ids`
- add `_key_properties['locations']` as the concatenation of each recording's locations

Mea1k fixes and MultiChannelRecordingExtractor locations

---

spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py

Adds an optional flag (lfp) to the parameters which enables it to parse lf.bin files properly. Without this modification, the current __init__ function only looks for AP channels, and will assume there are 0 channels of data in an lf.bin file. Tested on my own ap.bin and lf.bin files and it works.

Allows SpikeGLXRecordingExtractor to extract LFP files

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

1. Replaced all nested if checks with single line assertion
2. Better organized initial metadata auto-population and defaults, including auto-creation of default device
3. Replaced dictionary definitions with literals
4. Replaced `print("Warning: ...")` with `warnings.warn(...)`
5. Enforced Numpy docstring/PEP8

Refactor of add_electrode_groups in NwbRecordingExtractor

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

Suggested by @bendichter on the [previous PR](https://github.com/SpikeInterface/spikeextractors/pull/459). 
Only change required to pass tests is the conversion of `units_table.id[:]` from `list` to `np.array` in order for the `ids == unit_id` to evaluate as intended.

refactor to helper function get_nspikes used in write_units

---

spikeextractors/extraction_tools.py
spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py
spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py
spikeextractors/extractors/mea1krecordingextractor/mea1krecordingextractor.py
spikeextractors/extractors/numpyextractors/numpyextractors.py
spikeextractors/extractors/openephysextractors/openephysextractors.py
spikeextractors/extractors/spikeglxrecordingextractor/readSGLX.py
spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
spikeextractors/multirecordingtimeextractor.py
spikeextractors/recordingextractor.py
spikeextractors/subrecordingextractor.py
spikeextractors/subsortingextractor.py
spikeextractors/tests/test_extractors.py
spikeextractors/tests/test_numpy_extractors.py

This PR implements the `get_ttl_events` method, which returns the frame time of digital channels used for synchronization.
The method signature is : `get_ttl_events(self, start_frame=None, end_frame=None, channel_id=0)`, where `channel_id` is the channel of the digital signal to be returned. 
The method returns:
- ttl_frames: np.array with frames at which TTL occur
- ttl_state: np.array of the same length with +1 (rising) and -1 (falling) 
Currently implemented in:
- SubRecordingExtractor
- MultiRecordingTimeExtractor
- NumpyRecrdingExtractor (for adde tests)
- SpikeGLXRecordingExtractor
- OpenEphysRecordingExtractor
- IntanRecordingExtractor
- Mea1kRecordingExtractor
- MaxOneRecordingExtractor

Implement get_ttl_events method for available extractors

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

I should have taken a closer look at this before OK'ing the last one for merge; after taking another look at the logic, as well as the default behavior of functions like `recording.get_shared_channel_property_names()`, I've removed some unnecessary if checks that were always tautologically getting called or ignored.

simple fix to add_electrode_group functionality

---

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py

Remove unused `shank_id` arg from `NeuroscopeSortingExtractor.get_unit_spike_train()`
Fixes https://github.com/SpikeInterface/spikewidgets/issues/69

Removed unused shank_id arg in NeuroscopeSortingExtractor

---

spikeextractors/baseextractor.py

Extractors external to spikeinterface (e.g. form `spikeforest_utils` or custom) might not have a `__version__`. This allows the version to be unknown.
Should fix: 
- https://github.com/SpikeInterface/spikeextractors/issues/476
- https://github.com/SpikeInterface/spikeinterface/issues/80
Note that even for external extractors, the `self._kwargs` HAVE to be set, otherwise the dumping mechanism does not work.

Let module version be unkkown when dumping to dict

---

spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py

Basically, when the `NwbRecordingExtractor.write_recording()` reaches [this step](https://github.com/catalystneuro/spikeextractors/blob/master/spikeextractors/extractors/nwbextractors/nwbextractors.py#L665-L669), the part of `IntanRecordingExtractor.get_traces()` that [indexes channels after it reads them from pyintan](https://github.com/catalystneuro/spikeextractors/blob/master/spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py#L55-L56) throws an indexing issue.
This indexing issue does not occur if your channel indices are consecutive starting from 0, and the current fix as of the submission of this PR has only been confirmed to work when extracting a single index (which is the main use for my current purposes).

bug fix for intan get_traces()

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

A very odd bug that avoided previous detection because other, non error-causing custom columns were added prior to 'group_name' which automatically created the electrode table (i.e., no longer `None`). and hence allowed the current step of `metadata_column['name']` to properly check its existence in the table.
However, if 'group_name' is the first such column to be added to a non-existent electrode table, it causes a downstream error. This PR fixes this for now, but I'll try to think of a more clever way to properly retrieve the safe keys for column additions at that step.

Additional hotfix to NwbRecordingExtractor.add_electrodes()

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

@bendichter If the traces return a non-memory map object, and the data generator is used, the `DataChunkIterator` does not know what the true channel dimension is and so leaves it as `unlimited`. Not a huge issue, but this fixes it.
@alejoe91 Opening as draft because I might include some data conversion type stuff here as well.
Note this branch also includes the `add_electrode` hotfix on the other PR, for testing purposes.

small changes to NwbRecordingExtractor add_electrical_series

---

spikeextractors/extractors/maxoneextractors/maxoneextractors.py
spikeextractors/extractors/mea1kextractors/mea1kextractors.py

The Mea1k/MaxOne system can also record spikes only. In that case, the channel activity can still be computed, but the `num_frames` must be extracted from the spike times.

Fixed Mea1k and MaxOne num_frames when only spikes are recorded

---

spikeextractors/recordingextractor.py
spikeextractors/sortingextractor.py
spikeextractors/tests/test_extractors.py

Functionality for copying epoch information from recording and sorting extractors. Will be used to fix downstream issues with disappearing epochs.

copy epochs and tests

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

1) Removed unused auxiliary function.
2) Added assertion to check and instruct users to not pass 'group' as an electrode metadata column any more since it is never used, and entirely overridden in functionality by 'group_name'. The docstring had actually indicated this since the refactor, but it was still possible to pass it in to no effect.

Add 'group' check to add_electrode

---

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py

Multiple `*.res.*` and `*.clu.*` files (one for each shank) as output of *Klusters* (*Neuroscope*) can potentially be located in the same folder next to a single `*.res` and `*.clu` file containing the data for all shanks.
Moreover, the generation of backup files ending with a tilde like `*.res.*~` by text editors like Emacs can cause failure of the `NeuroscopeSortingExtractor` or `NeuroscopeMultiSortingExtractor` classes.
Finally, `NeuroscopeMultiSortingExtractor` would not accept data, if data was recorded with only one shank, i.e. if there were only one `*.res.1` and `*.clu.1` file (because of assertion in line 406).
The introduced changes make NeuroscopeSortingExtractor only look for *.res and *.clu and NeuroscopeMultiSortingExtractor only look for `*.res.*` and `*.clu.*` while making …

Allowed for overall and single Neuroscope files

---

spikeextractors/cacheextractors.py
spikeextractors/extraction_tools.py
spikeextractors/extractors/mdaextractors/mdaextractors.py
spikeextractors/recordingextractor.py
spikeextractors/tests/test_tools.py

This PR allows one to use `n_jobs` to speed up writing to binary (e.g. Caching)
A little benchmark:
```
import spikeextractors as se
import spiketoolkit as st
import time
rec, sort = se.example_datasets.toy_example(duration=300, num_channels=32, dumpable=True)
rec = se.MultiRecordingTimeExtractor([rec, rec, rec, rec, rec]) # increase length
rec = st.preprocessing.bandpass_filter(rec)
t_start = time.time()
rec.write_to_binary_dat_format(save_path='test_1_job.dat', chunk_mb=100, n_jobs=1, verbose=True, dtype='int16')
t_stop = time.time()
print(t_stop - t_start) 
t_start = time.time()
rec.write_to_binary_dat_format(save_path='test_4_job.dat', chunk_mb=100, n_jobs=4, verbose=True, dtype='int16')
t_stop = time.time()
print(t_stop - t_start)
```

Write binary dat in parallel

---

spikeextractors/extractors/nwbextractors/nwbextractors.py
spikeextractors/recordingextractor.py

- Also changed the docstrings for `time_to_frame` and `frame_to_time` as they also accept an array as input

Nwb write functions can use timestamps instead of rate

---

spikeextractors/extractorlist.py
spikeextractors/extractors/neuroscopeextractors/__init__.py
spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py
spikeextractors/tests/test_extractors.py

@bendichter @alejoe91 The PeyracheA dataset from the Buzsaki lab reports some raw data broken up by chronological epochs. Considering this the structure used there as standard for the Neuroscope format, this class uses the `MultiRecordingTimeInterface` to  read in these multiple `.dat` files and combine them into a single extractor for conversion purposes. Highly analogous to the `NeuroscopeMultiSorting` extractor.

Add neuroscope multirecordingtime extractor

---

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py
spikeextractors/extractors/nwbextractors/nwbextractors.py

@bendichter @alejoe91 Extends the `NeuroscopeRecordingExtractor` to be used on the nearly identically formatted `.eeg` files for use in the nwb-conversion-tools LFP data interfaces.
Also minor refactoring of `NwbRecordingExtractor.add_electrical_series`.

Extend neuroscope recording to lfp

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

@CodyCBakerPhD the `nwbfile: pynwb.NWBFile` in the `check_module` function is messing up downstream tests because `pynwb` is not a requirement.

Fix check module for nwb import

---

spikeextractors/extractors/maxoneextractors/maxoneextractors.py
spikeextractors/extractors/mcsh5recordingextractor/mcsh5recordingextractor.py
spikeextractors/extractors/mea1kextractors/mea1kextractors.py
spikeextractors/extractors/mearecextractors/mearecextractors.py
spikeextractors/extractors/nwbextractors/nwbextractors.py

**IMPORTANT**
@samuelgarcia @magland @colehurwitz @mhhennig @bendichter 
Hi guys, found this nasty bug in h5-based extractors. 
The bug occurs when traces are retrieved from h5-based extractors (MEArec, NWB, MCSH5, Mea1k, MaxOne) using a subset of **UNSORTED** `channel_ids`, which fortunately it's not a common use case.
I found the bug because I had to sort and concatenate several recordings with different channel maps and the traces were looking weird. 
All of our benchmarks are fine because we always use all channels.

Fix h5 unsorted channel_ids in get_traces

---

spikeextractors/extractors/cedextractors/cedrecordingextractor.py

This prevents the extractor to fail when the `smrx_channel_ids` is empty.
Also renamed `smrx_ch_inds ` --> `smrx_channel_ids` to keep semantics similar to SI

CEDREcordingExtractor: assert that the list of channels is not empty

---

spikeextractors/recordingextractor.py
spikeextractors/tests/test_extractors.py

Added functions for clearing location and group properties. Fixed small inconsistencies and refactored. Added new tests.
I also made it so that if any channel location has a `np.nan` value, then it will not be listed as a property (previous implementation was that if there were any **non**-`np.nan` values, then it would be listed as a property). Thoughts on this @alejoe91 ?

added clear properties

---

.travis.yml
spikeextractors/extractors/nwbextractors/nwbextractors.py
spikeextractors/tests/test_extractors.py

@bendichter @alejoe91 A couple small fixes for things that popped up in the CED pipeline.
1) Apparently, it's possible for the occasional recording extractor to have a sampling frequency that is an integer. Something in pynwb/hdmf wanted it to be a float, so this casts it.
2) For context, max_channel was a property we developed way back for the Yuta set to denote reference electrodes and link them in the spiking units table.
Apparently this same key is automatically set by certain types of returned sorting extractors from `spikesorters` in our pipelines. This isn't an issue in and of itself, _however_ the use of `quick_write` methods allow a possibility that we write a sorting extractor prior to writing any recording information, including an electrode table and hence we cannot complete …

small fixes to write methods for nwb recording and sorting

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

@alejoe91 Some undetected errors from earlier today.
Namely, the templates unit property which pops up automatically from some `spikesorters` is actually a tuple of values, which confuses `np.isnan` in that check.

small fixes to NwbSortingExtractor.write_sorting

---

spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py

https://github.com/SpikeInterface/spikeextractors/commit/16de17289117d0556e9e225a46cd22f60292f5fe broke the `SpikeGLX` set_gains. Fixed by explicitly using keywords.
Fixes: https://github.com/SpikeInterface/spikeextractors/issues/535

Fix spikeglx set gain

---

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py
spikeextractors/extractors/nwbextractors/nwbextractors.py
spikeextractors/sortingextractor.py

@alejoe91 Standardized styling and format for the four extractors, updated docstrings, removed unneeded absolute paths. Very minor changes overall, but makes it much easier to view the changelogs of some upcoming PR's inheriting from this.
Biggest computational change is the removal of `np.loadtxt`, [which is quite slow](https://stackoverflow.com/questions/52232559/numpy-loadtxt-is-way-slower-than-open-readlines), and instead just read the lines directly.

Neuroscope refactoring

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

@alejoe91 When trying to instantiate a `NwbRecordingExtractor` on a NWBFile that was built under a previous version (having trouble pinning down the exact version this was changed in `pynwb`), epoch information is keyed in a different naming convention and it throws an error.
This fixes the error by detecting which naming convention is present in the epochs.

small fix to reading older nwb format

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

Fix issue 546
@alejoe91 Per internal discussion, checking if the string equivalent of the channel's group id is in the `nwbfile.electrode_groups` before attempting the last-ditch index search.
Also improved metadata defaulting to allow a partial metadata dictionary to be passed. Also added assertion with more informative message in the case where no electrode table is written by consequence of the `continue` warning in the iteration.
@khl02007 This ought to fix your issue, if you can give this branch a try.

Fix issue 546

---

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py
spikeextractors/extractors/nwbextractors/nwbextractors.py
spikeextractors/extractors/phyextractors/phyextractors.py

@alejoe91 Various debugs for converting the PetersenP dataset from the Buzsaki lab.
1) Though I've run into the situation before, where there are multiple .xml files in a single folder, this is the first time those extra ones haven't been accidental or non-informative. There are actually multiple valid and useful .xml files, so I'm just adding a `xml_file_path` argument to Neuroscope as a manual bypass of the auto-detection.
2) The newer versions of the Neuroscope format call the `.eeg` LFP files `.lfp`. Same exact internal format though.
3) Added annotation typing to Phy extractors for their new data interfaces over on nwb-conversion-tools.

Debugging for petersen

---

spikeextractors/multirecordingchannelextractor.py
spikeextractors/recordingextractor.py
spikeextractors/tests/test_extractors.py

Fixes #553 
Quick explanation: `MultiRecordingChannelExtractor` used to fetch properties from each internal extractor, as a result, the `._properties` dictionary was empty. As `copy_channel_properties` was sometimes deepcopying the `._properties` dictionary, this would cause properties to not be inherited by the `CacheRecordingExtractor` when wrapping a `MultiRecordingChannelExtractor`.
Fix: `MultiRecordingChannelExtractor` now fills the `._properties` dictionary with all of the internal extractor properties and then does not reference the internal extractor properties anymore. This means that **changes to the multiextractor properties will no longer change the internal extractor properties**. Is this behaviour ok @alejoe91 ? I think it is much more straightforward and less prone to error …

property fixes multichannel

---

spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py

Fixes https://github.com/SpikeInterface/spikeextractors/issues/564 and https://github.com/SpikeInterface/spikeextractors/issues/561
https://github.com/SpikeInterface/spikeextractors/issues/564
The problem was that the conditions to define AP, LF, or NIDQ recordings were based on the assumptions that `imec0` is in the file name. However, some file names can also only have `imec`
https://github.com/SpikeInterface/spikeextractors/issues/561
The staggered configuration needed to be added 'manually'. Basically every other row will be shifted by x_pitch // 2. The x_pitch has been updated to 32 (16 * 2), as this is the actual distance of the electrodes on the same row.

Fix SpikeGLX locations and channel names

---

spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py
spikeextractors/extractors/phyextractors/phyextractors.py

- Enable to have `channel_ids` as a subset of the number of channels in the binary file (fixes https://github.com/SpikeInterface/spikeextractors/issues/387)
- Added `gain_first` argument to control how `gain` and `offset` should be applied
- Added docstring
- Removed `load_waveforms` and `verbose` arguments. Waveforms must be computed with `spiketoolkit` or uploaded externally
- dded docstrings

Updates to BinDat and Phy extractors

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

@alejoe91 The `buffer_mb` argument has been available at the `add_electrical_series` level for quite a while, but was never able to be specified at the highest level of `write_recording`.
Now that we are running multiple large-scale raw data conversions in parallel, a facet unlikely to soon change, this argument will give us a much greater degree of control over the processing resource specification.

allow buffer_mb argument in NwbRecordingExtractor.write_recording()

---

spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py

Accept  now
- imec.ap.bin
- imec.lf.bin
- imecX.lf.bin      with X the recording number
- imecX.ap.bin
close #583 
@gmaggi  Do you think you could checkout on this branch on the cluster please ? I want to verify that the pipeline is not breaking later with the imec1 file and also Hanna needs to send her jobs as soon as possible. 
@alejoe91 , @samuelgarcia    should i add some tests to keep track of the allowed filenames ?

Modified assertion check to accept all imecX.lf or imecX.ap file as input

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

@alejoe91 Sorry I didn't catch it during review of the return_scaled PR, though interesting none of the GIN tests catch it either. Must be that none of the GIN tests make recording extractors with multiple groups? Or we don't test GIN alongside metadata passing, and the metadata auto-pop we made at each step completely handles internal groups without error.
Either way, without this `elif` condition, any passed metadata gets overridden by the defaults at call.

fixed metadata issues arising in new version

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

fix #587 
Part (a) of that issue dealt with auto-population of the electrical series name, which is now properly fixed.
Part (b) is the odd error that occurs, for example, if the electrode ids in the nwbfile.electrodes table were not added in increasing order - the original direct indexing of the electrical series region (which are indexes of ids in the electrodes table) through the table caused an error through h5py and is now fixed by list compression passing through a single index at a time.
Part (c) is unfortunately the fact that the electrode ids weren't unique to begin with, making it an invalid NWBFile. Reaching out to try to fix in the independent software, but [a PR fix has been proposed on PyNWB](https://github.com/NeurodataWithoutBorders/pynwb/pull/1344), at least.

fix issue 587

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

allow user-defined metadata when saving to nwb from non-nwb extractor

allow user-defined metadata when saving to nwb from non-nwb extractor

---

spikeextractors/multirecordingchannelextractor.py
spikeextractors/multirecordingtimeextractor.py
spikeextractors/subrecordingextractor.py

This PR fixes a multiple scaling issue when multiple Sub or Multi RecordingExtractors are constructed. 
Originally, all properties are copied to the Sub-Multi extractors, including gains and offsets. Weh retrieving scaled traces, each extractor would apply the scaling, resulting in multiple scaling. 
This PR fixes this behavior by clearing gains and offsets of Sub and Multi extractors.

Clear gains and offsets for sub and multi rec extractors 

---

requirements-dev.txt
spikeextractors/extractors/neoextractors/neobaseextractor.py

@alejoe91 
I only changed 1 thing: Forced chan_ids to be np.ndarray of integers. In python-neo it is now by default a np.ndarray of 'U64's, i.e. strings. See here for the changes to python-neo: https://github.com/NeuralEnsemble/python-neo/pull/949

Neoextractors channel ids patch

---

.github/workflows/python-package.yml

If works - an alternative to #623 (which would pin git-annex version)
this is just a wild guess/attempt.

BF?: do configure git in the python-package.yaml CI

---

spikeextractors/extractors/nwbextractors/nwbextractors.py

I changed the error message that appears when trying to reading an nwbsortingextractor from an nwb file, when there is no acquisition data in the file from which to read the sampling frequency. The error message is now more informative, informing the user that specifying the `sampling_frequency` paramater will fix the error. 
@alejoe91 I did not change anything in the code, only the error message, so this should be mergable right away. 
Oh, but I already have changes from axonaextractor in here. Should I branch from spikeinterface:master and redo?

Nwbsortingextractor err msg

---

spikeextractors/extractors/nwbextractors/nwbextractors.py
spikeextractors/testing.py
tests/test_extractors.py

Extend options when writing to nwb. 
See https://github.com/catalystneuro/nwb-conversion-tools/pull/172
Allows `se.NwbRecordingExtractor.write_recording()` to choose between three options for type of electrical series:
- `raw` will save it in acquisition
- `processed` will save it as FilteredEphys
- `lfp` will save it as LFP
If no nwb metadata is passed, default values are used. 
If nwb metadata with many electrical_series keys is passed, the arg `es_key` should indicate which specific metadata key corresponds to the data being written.

NwbRecordingExtractor.write_recording extended options

---

spikeextractors/extractors/mearecextractors/mearecextractors.py

Sorry I have been MIA for a while (working on finishing up my thesis).  I caught this issue when helping someone getting spikeinterface working. Basically, the channel_ids are converted into a numpy array with the sort operation and will cause the slicing to fail. You have to convert it to a list to make it work. Surprisingly, casting it as a list does not work, you have to use numpy.tolist().

issue with slicing in mearec

---

spikeextractors/extractors/cedextractors/cedrecordingextractor.py
spikeextractors/extractors/cedextractors/utils.py
tests/test_extractors.py

- fix off-by-one error in num_frames, nMax, end_frame in cedrecordingextractor
- add test case for CED extractor issue: last element missing from traces
- resolves #648

fix CED traces missing last element

---

spikeextractors/sortingextractor.py

Related to: https://github.com/SpikeInterface/spikeinterface/issues/179#issue-927586849
When caching a sorting extractor from e.g. Mountainsort on data with channel groups, the `group` property is lost after caching. This is because the multisorting extractor does not have a `_properties` attribute, instead it has a list of sorting extractors with `_properties` attributes. Therefore, here we avoid deep copying the `_properties` attribute when caching.

avoid deepcopy for multisorting extractors

---

spikeextractors/extractors/cedextractors/utils.py

- reduces RAM usage of [get_traces](https://github.com/SpikeInterface/spikeextractors/blob/118aa9d2acb395e76bcb40c80a9db6f28a054230/spikeextractors/extractors/cedextractors/cedrecordingextractor.py#L101) (21GB -> 13GB for a small test smrx file with 32 channels)
- could be further reduced by using a smaller np data type (which it looks like [neo already does](https://github.com/samuelgarcia/python-neo/blob/master/neo/rawio/cedrawio.py#L82))

return CED data as np.array instead of python list

---

spikeextractors/extractors/neoextractors/neobaseextractor.py

there are some blackrock files that dont have a unit (V,mV,uV) specified at all (its an empty string in the .nsx header itself). 
I think we should be able to handle such cases also, though ideally its undesirable and an edge case. 
Do you think assuming non-existent units as micro-Volts makes sense?

optional channel unit value

---

full_requirements.txt
spikeextractors/extractors/nwbextractors/nwbextractors.py

One of the things we were aware of from PR #600 and issue #587 that may have gotten a bit lost in the monster changelog that was PR #571, was how the NwbRecordingExtractor has to deal with the constraint that h5 datasets must have their data accessed by slices in sorted (strictly increasing) order.
This came up as I was building GIN tests for the SpikeGadgets format on nwb-conversion-tools, since both instances of that data on GIN have scrambled channel_id order. Note that SpikeGadgets did not make it into this the GIN testing for this version of spikeextractors, hence why this has never cropped up so formally before.
Anyway, this fixes the issue for me, as seen [here](https://github.com/catalystneuro/nwb-conversion-tools/pull/246) Also should be more efficient with the new `argsort` …

NwbRecording extractor get_traces() with scrambled ids

---

spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py

compressed .bin files (used mainly by IBL) is stored as shape (samples, channels) while `SpikeGLXRecordingExtractor` expects the transpose of this. 
Currently opening the .cbin format using mtscomp cannot be transposed initially since its compressed and not stored as a np.memmap. So to actually support .cbin we would have to add if loops to transpose what ever is retrieved. It would be better to create a new class like `SpikeGLXCompressedRecordingExtractor` or something or drop the support altogether (new spikeinterface any does not support this as neo does not). 
When I tried opening a .cbin file, the method ended up chopping the time dimension instead of the channels
@samuelgarcia @alejoe91 what do you guys think? : letting go of being able to open .cbin files or creating a new class?

remove .cbin support

---

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py

@alejoe91 Adding capability for setting explicit `xml_file_path` for other Neuroscope extractors. We previously added it only for the `RecordingExtractor`.
Sorry, I know this is in legacy status. This is probably our last time using this before making the jump to SI2.

Neuroscope sorting xml fix

---

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py

Ramon discovered an issue with a newly seen case of Neuroscope format; where the unit IDs in the `.txt` file are not in the usual 0-indexed order. Seeing if this fixes the issue for him.

fix to NeuroscopeSorting IDs

---

spikeextractors/extractors/cellexplorersortingextractor/cellexplorersortingextractor.py

The purpose of this pull request is to fix/update some reading problems with the reading of matlab files in the `CellExplorerExtractor` 
1) We add capabilities to consistently read `sessionInfo` and and `spikes.Info` files independently on the matlab format (that is either `scipy.io` or `hdf5storage`).
2) Add the location of the the matlab files as an optional parameter in the extractor.
3) Add the sampling frequency as an optional parameter so a reading of `SessionInfo` is not required.

Adding matlab reading capabilities for new format in CellExplorerExtractor

---

requirements-dev.txt

Avoid hdbscan installation issues for TDC (GIN tests are skipped and roundtrip test is not relevant anymore)

Avoid installing tridesclous for tests
