.travis.yml, pytest.ini, setup.py, spikeinterface/MultiRecordingExtractor.py, spikeinterface/RecordingExtractor.py, spikeinterface/SubRecordingExtractor.py, spikeinterface/__init__.py, spikeinterface/extractors/mdaextractors/mdaextractors.py, spikeinterface/extractors/numpyextractors/numpyextractors.py, spikeinterface/extractors/nwbextractors/__init__.py, spikeinterface/extractors/nwbextractors/nwbextractors.py, tests/test_extractors.py
Also changed testing setup to solve segfault problems -- use pytest now rather than old method.
=> Fix timeToFrame and frameToTime throughout and add nwb recording extractor

.travis.yml, pytest.ini, setup.py, spikeinterface/MultiRecordingExtractor.py, spikeinterface/RecordingExtractor.py, spikeinterface/SubRecordingExtractor.py, spikeinterface/__init__.py, spikeinterface/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeinterface/extractors/hs2sortingextractor/hs2sortingextractor.py, spikeinterface/extractors/mdaextractors/mdaextractors.py, spikeinterface/extractors/numpyextractors/numpyextractors.py, spikeinterface/extractors/nwbextractors/__init__.py, spikeinterface/extractors/nwbextractors/nwbextractors.py, tests/test_extractors.py
- changed unit testing to produce integer raw data as in Biocam files
- commented out getChannelInfo unit test
=> Added write functions for Biocam and HS2 extactors

spikeinterface/RecordingExtractor.py, spikeinterface/SortingExtractor.py, spikeinterface/tools.py
tools.py
#43 Standardized the argument names and formats to make it fit with the rest of the repo. Added extrac documentation and removed commented out code
Cleaned new extractor code to fit with rest of the extractor code.
=> Fixed merge and argument names in tool. Cleaned code in extractors

.travis.yml, setup.py, spikeinterface/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeinterface/extractors/hs2sortingextractor/hs2sortingextractor.py, spikeinterface/extractors/klustasortingextractor/klustasortingextractor.py, spikeinterface/extractors/mdaextractors/mdaextractors.py, spikeinterface/extractors/mearecextractors/mearecextractors.py, spikeinterface/extractors/nwbextractors/nwbextractors.py, spikeinterface/extractors/openephysextractors/openephysextractors.py, spikeinterface/tools.py
- removed dependency and added helper messages for: pyopenephys, pynwb, mountainlab_tools
- fix a debug print in mearecextractors
=> removed package specific dependencies 

spikeinterface/SortingExtractor.py
Added:
getUnitSpikeFeatures(self, unit_id, feature_name, start_frame=None, end_frame=None):
getUnitSpikeFeatureNames(self, unit_id):
They both throw unimplemented errors if not implemented and their implemenation is up to the discretion of the subclasses.
=> Created getUnitSpikeFeatures and getUnitSpikeFeatureNames. Unimplemented

spikeextractors/SortingExtractor.py, spikeextractors/__init__.py, spikeextractors/extractors/intanrecordingextractor/__init__.py, spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py, spikeextractors/extractors/kilosortsortingextractor/kilosortsortingextractor.py, spikeextractors/extractors/openephysextractors/openephysextractors.py
- added recording extractor for rhd and rhs recordings
- small fixes here and there
=> Intanextractors

spikeextractors/__init__.py, spikeextractors/extractors/tridesclousextractor/__init__.py, spikeextractors/extractors/tridesclousextractor/tridesclousextractor.py
=> tridesclous extractor.

spikeextractors/extractors/tridesclousextractor/tridesclousextractor.py
this is a small bug fix to autoselect the good channel group in tridesclous folder.
needed for sorter in class.
=> Fix bug when several channel group inside one folder.

.gitignore, README.md, spikeextractors/extractors/mdaextractors/mdaextractors.py, spikeextractors/extractors/mdaextractors/mdaio.py
@colehurwitz31 and all, please take a look at this pull request.
I have revised some of the language in the readme. Feel free to reject or accept any of those modifications.
I have also updated the mda extractors, in preparation to using this repo as a dependency of spikeforest rather than having my own snapshot.
Importantly we will no longer have dependencies on mountainlab_pytools and kbucket.
=> Edit README, update mda extractors, and remove dependencies on kbucket and mountainlab_pytools

spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py
=> Add offset to BinDatRecordingExtractor

spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py, spikeextractors/extractors/mearecextractors/mearecextractors.py
- MEArec now uses memmappped raw data access (via h5py)
- minor Biocam fixes
=> Fixes in MEArec and Biocam recording extractors

spikeextractors/tools.py
=> Bug: wrong logic in loadProbeFile.

spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py, tests/test_extractors.py
getUnitProperty now default implementation. HS2 specific properties loaded in during initialization.
=> Fixed properties in HS2 extractor.

README.md, setup.py, spikeextractors/RecordingExtractor.py, spikeextractors/SortingExtractor.py, spikeextractors/__init__.py, spikeextractors/extractorlist.py, spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeextractors/extractors/exdirextractors/exdirextractors.py, spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py, spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py, spikeextractors/extractors/kilosortsortingextractor/kilosortsortingextractor.py, spikeextractors/extractors/klustasortingextractor/klustasortingextractor.py, spikeextractors/extractors/mdaextractors/mdaextractors.py, spikeextractors/extractors/mearecextractors/mearecextractors.py, spikeextractors/extractors/openephysextractors/openephysextractors.py, spikeextractors/extractors/physortingextractor/physortingextractor.py, spikeextractors/extractors/spykingcircussortingextractor/spykingcircussortingextractor.py, spikeextractors/extractors/tridesclousextractor/tridesclousextractor.py
Planning to do the same for preprocessing and postprocessing.
=> Added extractor list, installation information, gui_params, naming, and installation messages.

spikeextractors/__init__.py, spikeextractors/extractorlist.py, spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/extractors/spikeglxextractor/__init__.py, spikeextractors/extractors/spikeglxextractor/spikeglxrecordingextractor.py, spikeextractors/tools.py
- read number of channels
- loads channel locations (assuming standard configuration)
=> Implemented SpikeGLX extractor for neuropixels

spikeextractors/extraction_tools.py, spikeextractors/extractors/exdirextractors/exdirextractors.py, spikeextractors/extractors/physortingextractor/physortingextractor.py
fixes include:
- enhanced phy sorting extractor capability (can load waveforms)
- fixes to load probe geometry
- improved exdir write sorting function
=> various fixes

spikeextractors/extractorlist.py, spikeextractors/extractors/phyextractors/__init__.py, spikeextractors/extractors/phyextractors/phyextractors.py, spikeextractors/extractors/physortingextractor/__init__.py
In the phy template gui output there are also a .dat file and all the information needed to instantiate a recording extractor.
Implemented here a `PhyRecordingExtractor`, which inherits from the `BinDatRecordingExtractor`
=> implemented phy recording extractor

spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py
* better reading performance for Biocam files
* should now correctly detect different brw formats
=> Extractor fixes for biocam and hs2

README.md
in 'from spikeextractors import se', must be 'import spikeextractors as se'
=> syntax for import spikeextractors typo correction

spikeextractors/SortingExtractor.py, spikeextractors/extractors/numpyextractors/numpyextractors.py
I implemented some GUI params for sorting extractor and removed some artifacts from the numpy extractors
=> GUI params for sorting extractors

spikeextractors/extractors/mearecextractors/mearecextractors.py
@samuelgarcia @colehurwitz this should solve many of spike sorting problems with MEArec :)
=> dump 3rd dimension in MEArec extractor by default

spikeextractors/extractorlist.py, spikeextractors/extractors/npzsortingextractor/__init__.py, spikeextractors/extractors/npzsortingextractor/npzsortingextractor.py, tests/test_npzsortingextractor.py
@alejoe91 @colehurwitz : I have implemented a very simple file format for sortign extractor.
I will be usefull to share result and send results for coprarison.
It use the NPZ from numpy format. Very simple.
Internally it store unit_ids+times+labels as vetor (+optional sampling_frequency very soon)
If it is OK for you could we merge this. I will add some function in spiketoolkit that will need this.
=> Implement a simple format based on npz

spikeextractors/extractors/exdirextractors/exdirextractors.py
Now exdir sorting extractor loads the unit attributes
=> improvement to exdir extractors

spikeextractors/CurationSortingExtractor.py, spikeextractors/MultiSortingExtractor.py, spikeextractors/SubSortingExtractor.py, spikeextractors/example_datasets/synthesize_random_firings.py, spikeextractors/example_datasets/synthesize_timeseries.py, spikeextractors/example_datasets/toy_example.py, spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py, spikeextractors/extractors/npzsortingextractor/npzsortingextractor.py, spikeextractors/extractors/numpyextractors/numpyextractors.py, tests/test_extractors.py, tests/test_npzsortingextractor.py
Adding some sampling frequency stuff in this pull request
=> Added sampling frequency and test for HS2 and other stuff [WIP]

spikeextractors/extractors/phyextractors/phyextractors.py
=> int -> int64

spikeextractors/extractors/npzsortingextractor/npzsortingextractor.py
This bug make the comparison study broken if sampling frequency is unkonwn.
=> Bug in npz when no sampling_rate

spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py
@alejoe91 Do any of the formats you added have this proble? Samuel made me realize that since write_sorting doesn't always write out the sampling frequency, we need to check to see if it is in the file.
=> Set to None if sampling not in folder

spikeextractors/extractors/exdirextractors/exdirextractors.py
fix channel ids in exdir extractors
=> exdir update

spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py
=> Loading extra information optional -- solves speed issues

spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py
Pre-load spike times, and fill dict in load_unit_info directly.
=> HS2 sorting extractor speed up

spikeextractors/MultiSortingExtractor.py, tests/test_extractors.py
Removed continuous multisorting extractor (thank goodness lol)
=> Made multisorting extractor only non-continuous

README.md, examples/1_recording_extractors.ipynb, examples/2_sorting_extractors.ipynb, examples/3_concatenating_recordings.ipynb, examples/4_concatenating_sortings.ipynb, spikeextractors/MultiRecordingChannelExtractor.py, spikeextractors/MultiRecordingTimeExtractor.py, spikeextractors/MultiSortingExtractor.py, spikeextractors/RecordingExtractor.py, spikeextractors/__init__.py, spikeextractors/extraction_tools.py, spikeextractors/extractors/tridescloussortingextractor/tridescloussortingextractor.py, tests/test_extractors.py
I created two new notebooks to show how to call and use these multiextractors and added some unit tests for them.
se.concatenate_recordings_by_time(recordings, epochs) --> MultiRecordingTimeExtractor
se.concatenate_recordings_by_channel(recordings, groups) --> MultiRecordingChannelExtractor
se.concatenate_sortings(sortings) --> MultiSortingExtractor
One thing I noticed, both the MultiSorting and MultiRecordingChannel extractor change the underlying channel properties of the recordings that they concatenated... that is fine, but when you pass in duplicate recordings or sortings, the set_property calls will overwrite each other... I don't think this is a problem though because we should be expecting different extractors to be passed in.
Let me know if this pull request is ready please! …
=>  All multi extractors are working and can be called with functions.

spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeextractors/extractors/exdirextractors/exdirextractors.py, spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py, spikeextractors/extractors/kilosortextractors/kilosortextractors.py, spikeextractors/extractors/klustaextractors/klustaextractors.py, spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py, spikeextractors/extractors/mdaextractors/mdaextractors.py, spikeextractors/extractors/mearecextractors/mearecextractors.py, spikeextractors/extractors/openephysextractors/openephysextractors.py, spikeextractors/extractors/phyextractors/phyextractors.py, spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py, spikeextractors/extractors/spykingcircusextractors/spykingcircusextractors.py, spikeextractors/extractors/tridescloussortingextractor/tridescloussortingextractor.py
Added update gui params. Basically, some formats already give locations to the extractors so the sorting algorithms can immediately start working. Other format do not provide locations so some kinda .csv or .prb file must be given to those. I wanted to make probe files loadable for all extractors though to eventually support group computation.
=> GUI params update -- probe path optional or not depending on format

spikeextractors/extractors/mearecextractors/mearecextractors.py
I'd like to be able to tell the mearec extractors NOT to worry about the file name suffix for mearec recordings.
=> option to not check suffix for mearec recordings - WIP

spikeextractors/extractors/mearecextractors/mearecextractors.py
- MEArecRecordingExtractor only loads recordings and channel_positions
- MEArecSortingExtractors only loads spiketrains
=> Speed up MEArec extractors 

spikeextractors/MultiSortingExtractor.py, spikeextractors/SortingExtractor.py
Very useful for quality metrics
=> Added epoch functionality to sorting extractor

spikeextractors/SubRecordingExtractor.py
get snippets wasn't correct shifted for the start frame
=> Fix bug in get snippets

spikeextractors/MultiRecordingChannelExtractor.py, spikeextractors/MultiRecordingTimeExtractor.py, spikeextractors/RecordingExtractor.py, spikeextractors/SubRecordingExtractor.py, spikeextractors/extraction_tools.py, spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeextractors/extractors/exdirextractors/exdirextractors.py, spikeextractors/extractors/mdaextractors/mdaextractors.py, spikeextractors/extractors/mearecextractors/mearecextractors.py, spikeextractors/extractors/numpyextractors/numpyextractors.py, tests/test_tools.py
@alejoe91 @bendichter 
Thoughts on setting and getting gain? I just implemented it in the same way we handle locations and groups (as a property that can be added and returned). In the initialization of the NWBRecordingExtractor, you can set the gains using this function. 
If you put a float/int, it will set all electrode gains to the same value
If you put a list/array_like of floats/ints, then it will set each electrode according to the list you gave as long as the lengths are the same.
=> Added gain setting and getting

docs/available_extractors.rst, spikeextractors/extractors/mcsh5recordingextractor/mcsh5recordingextractor.py
=> Removed unused variable and added documentation

spikeextractors/extraction_tools.py
`channels_id_in_group` loaded in all cases
=> small load_probe_file fix

spikeextractors/extractors/neuroscopesortingextractor/__init__.py, spikeextractors/extractors/neuroscopesortingextractor/neuroscopesortingextractor.py
=> add neuroscope (name TBD) format extractor

examples/2_sorting_extractors.ipynb, spikeextractors/extraction_tools.py, spikeextractors/extractors/exdirextractors/exdirextractors.py, spikeextractors/extractors/klustaextractors/klustaextractors.py, spikeextractors/extractors/phyextractors/phyextractors.py, spikeextractors/multisortingextractor.py, spikeextractors/sortingextractor.py, tests/test_extractors.py
Added new tests as well for the shared name functions as well
=> Added shared unit and feature name functions

spikeextractors/extractors/spikeglxrecordingextractor/readSGLX.py
I disabled matplotlib functionality in spikeglx as it isn't used
=> disabled matplotlib functionality in spikeglx

spikeextractors/extractors/mdaextractors/mdaextractors.py
=> unit properties for mda

spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeextractors/extractors/exdirextractors/exdirextractors.py, spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py, spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py, spikeextractors/extractors/kilosortextractors/kilosortextractors.py, spikeextractors/extractors/klustaextractors/klustaextractors.py, spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py, spikeextractors/extractors/mcsh5recordingextractor/mcsh5recordingextractor.py, spikeextractors/extractors/mdaextractors/mdaextractors.py, spikeextractors/extractors/mearecextractors/mearecextractors.py, spikeextractors/extractors/neuroscopesortingextractor/neuroscopesortingextractor.py, spikeextractors/extractors/npzsortingextractor/npzsortingextractor.py, spikeextractors/extractors/numpyextractors/numpyextractors.py, spikeextractors/extractors/nwbextractors/nwbextractors.py, spikeextractors/extractors/openephysextractors/openephysextractors.py, spikeextractors/extractors/phyextractors/phyextractors.py, spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py, spikeextractors/extractors/spykingcircusextractors/spykingcircusextractors.py, spikeextractors/extractors/tridescloussortingextractor/tridescloussortingextractor.py, spikeextractors/recordingextractor.py, spikeextractors/sortingextractor.py
Important changes to file API:
Added:
- 'is_writable'
- 'mode' (file, dir, file_or_dir, custom) --> Custom currently covers one case that is unique (neuroscope). 
-- Arguments (based on mode): file --> file_path, dir --> dir_path, file_or_dir --> file_or_dir_path, custom --> anything
- Fixed gui params
@alejoe91 @samuelgarcia If you could check each extractor to make sure what I put makes sense, that would be very helpful. It was a tedious task and I may have make a mistake.
=> Important changes to file API (mode, is_writable, gui_params)

spikeextractors/extraction_tools.py, spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py
frames_first=True --> time_axis = 0
=> changes to bindat

spikeextractors/extraction_tools.py, spikeextractors/extractors/mcsh5recordingextractor/mcsh5recordingextractor.py
- clean up of MCSextractor (tested)
- use memmap.transpose instead of np.transpose in read_biniary
=> clean up mcsh5 extractor

spikeextractors/extractors/numpyextractors/numpyextractors.py
Added doc_strings and docs about NumpyExtractors
@teristam
=> Docs numpy

spikeextractors/cacherecordingextractor.py, spikeextractors/extraction_tools.py, spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/recordingextractor.py, tests/test_tools.py
last API change before release
=> chunksize -> chunk_size

spikeextractors/extractors/mcsh5recordingextractor/mcsh5recordingextractor.py
Previouly, `MCSH5RecordingExtractor` only supports loading data from 'stream0'. The following changes are made to support changing stream:
1. added 3 new methods, `set_stream_id()`, `get_stream_id()` and `get_available_stream_ids()`;
2. added an argument 'stream_id' to the function `openMCSH5File()` to specify the group path.
@colehurwitz Please test on Linux.
=> Updated MCSH5RecordingExtranctor to support changing stream

spikeextractors/extraction_tools.py
=> rEmoved inplace probe loading

spikeextractors/recordingextractor.py, spikeextractors/sortingextractor.py
I wanted a unique ID for each extractor that was created in a session. This is useful for naming temporary files, etc., when working with many Recordings and Sortings. What do you think @samuelgarcia ?
=> unique id (from counter)

spikeextractors/sortingextractor.py, spikeextractors/subsortingextractor.py, tests/test_extractors.py
#298 (fix in sortingextractor, subsortingextractor, and extra tests).
=> fix index issue spike features

.travis.yml, spikeextractors/extractorlist.py, spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/extractors/shybridextractors/__init__.py, spikeextractors/extractors/shybridextractors/parameters_template, spikeextractors/extractors/shybridextractors/shybridextractors.py, tests/test_extractors.py
- added shybrid recording and sorting extractor
- also implemented the static write methods for both extractors
=> add shybrid compatibility to spikeinterface

spikeextractors/extractors/mcsh5recordingextractor/mcsh5recordingextractor.py
attempt to fix https://github.com/SpikeInterface/spiketoolkit/issues/275
@McD-NMI can you try this out and see if it fixes the problem and looks correct?
=> Fix mcsh5 channel order bug

spikeextractors/extractors/shybridextractors/shybridextractors.py, spikeextractors/extractors/spikeglxrecordingextractor/readSGLX.py
Spikeglx was instantiating (but not using) two arrays that were the same size as the data! I disabled those..
=> memory issues spikeglx (fix)

setup.py, spikeextractors/extractorlist.py, spikeextractors/extractors/neoextractors/__init__.py, spikeextractors/extractors/neoextractors/neobaseextractor.py, spikeextractors/extractors/neoextractors/neuralynxextractor.py, spikeextractors/extractors/neoextractors/plexonextractor.py
This is a prrof of concept of extractors based on neo.
This is NOT tested.
This is a base for discussion.
#170
#224 
@colehurwitz @alejoe91 tell me what you think.
@bendichter  : I started with plexon as you requested this. If you have time to try this. This is cool.
@colehurwitz @alejoe91 : if you are happy with this, you must swear that you will help to port extractors to neo.rawio for instance openephys, spikeglx, mearec, biocam, exdir, ...
=> Proof of concept of neo based extactors.

spikeextractors/extraction_tools.py, spikeextractors/extractors/mdaextractors/mdaextractors.py, spikeextractors/extractors/mdaextractors/mdaio.py
This is done by directly writing the MdaHeader and appending the binary data using the `write_to_binary_dat_format` (which now can directly appen to a file handle)
=> Added chunking mechanism to mda 

.travis.yml, spikeextractors/extractors/kilosortextractors/kilosortextractors.py, spikeextractors/extractors/phyextractors/phyextractors.py, spikeextractors/subsortingextractor.py
- phy: property->property_name
- ks: KSLabel is checked for each unit, not as shared property
=> ks and phy small fixes

spikeextractors/baseextractor.py, spikeextractors/extractors/mdaextractors/mdaextractors.py
- deepcopy `kwargs` in `load_extractor_from_dict`
- `'max_channel` property to `'mda_max_channel` in `MdaSortingExtractor`.
=> Deepcopy kwargs in load_extractor

spikeextractors/baseextractor.py, spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeextractors/extractors/exdirextractors/exdirextractors.py, spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py, spikeextractors/extractors/kilosortextractors/kilosortextractors.py, spikeextractors/extractors/klustaextractors/klustaextractors.py, spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py, spikeextractors/extractors/mcsh5recordingextractor/mcsh5recordingextractor.py, spikeextractors/extractors/mdaextractors/mdaextractors.py, spikeextractors/extractors/mea1krecordingextractor/mea1krecordingextractor.py, spikeextractors/extractors/mearecextractors/mearecextractors.py, spikeextractors/extractors/nixioextractors/nixioextractors.py, spikeextractors/extractors/numpyextractors/numpyextractors.py, spikeextractors/extractors/nwbextractors/nwbextractors.py, spikeextractors/extractors/openephysextractors/openephysextractors.py, spikeextractors/extractors/phyextractors/phyextractors.py, spikeextractors/extractors/shybridextractors/shybridextractors.py, spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py, spikeextractors/extractors/spykingcircusextractors/spykingcircusextractors.py
This is to accomodate the `NumpyRecordingExtractor`, which can be dumpable (if `timeseries` is a npy file), or not dumpable (if `timeseries` is a numpy array)
=> is_dumpable is an object variable, not a statc variable

spikeextractors/cacherecordingextractor.py, spikeextractors/extractorlist.py, spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeextractors/extractors/exdirextractors/exdirextractors.py, spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py, spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py, spikeextractors/extractors/kilosortextractors/kilosortextractors.py, spikeextractors/extractors/klustaextractors/klustaextractors.py, spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py, spikeextractors/extractors/mcsh5recordingextractor/mcsh5recordingextractor.py, spikeextractors/extractors/mdaextractors/mdaextractors.py, spikeextractors/extractors/mea1krecordingextractor/mea1krecordingextractor.py, spikeextractors/extractors/mearecextractors/mearecextractors.py, spikeextractors/extractors/neoextractors/neobaseextractor.py, spikeextractors/extractors/neuroscopesortingextractor/neuroscopesortingextractor.py, spikeextractors/extractors/nixioextractors/nixioextractors.py, spikeextractors/extractors/npzsortingextractor/npzsortingextractor.py, spikeextractors/extractors/nwbextractors/nwbextractors.py, spikeextractors/extractors/openephysextractors/openephysextractors.py, spikeextractors/extractors/phyextractors/phyextractors.py, spikeextractors/extractors/shybridextractors/shybridextractors.py, spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py, spikeextractors/extractors/spykingcircusextractors/spykingcircusextractors.py, spikeextractors/multisortingextractor.py, spikeextractors/subrecordingextractor.py, spikeextractors/subsortingextractor.py
As discussed with @alejoe91 , I plan to move all GUI logic to spikely to disentangle GUI logic from spikeinterface.
=> removed gui params and exporter terminology

spikeextractors/cacherecordingextractor.py, spikeextractors/tests/test_extractors.py
check if the file is `tmp` in CacheRecordingExtractor
=> is_tmp in CacheRecording

spikeextractors/extractors/klustaextractors/klustaextractors.py, spikeextractors/tests/test_extractors.py
Here my implementation of adding 'cluster_group' and 'cluster_group_name' as unit properties.
I slightly updated the way of reading the data from the .kwik files, as I think this way it's easier to see wherefrom data in the hdf5 tree is loaded.
=> klusta extractor; add 'cluster_group' and 'cluster_group_name' as unit properties

spikeextractors/sortingextractor.py
=> units spike train implemented

spikeextractors/sortingextractor.py
=> Cast features to array at retrieval

spikeextractors/__init__.py, spikeextractors/cacheextractors.py, spikeextractors/cacherecordingextractor.py, spikeextractors/extractors/kilosortextractors/kilosortextractors.py, spikeextractors/extractors/phyextractors/phyextractors.py, spikeextractors/tests/test_extractors.py
+ remove `PhySortingExtractor.write_sorting()` to avoid confusion
=> CacheSortingExtractor + fixes to CacheRecordingExtractor

spikeextractors/example_datasets/toy_example.py, spikeextractors/extraction_tools.py
=> Cast dtype to np.dtype before .itemize

spikeextractors/tests/test_extractors.py, spikeextractors/tests/utils.py
tests forhttps://github.com/SpikeInterface/spikeextractors/pull/372
=> Improve tests for dump mechanisms

spikeextractors/recordingextractor.py
If locations are not set, do not return it as a shared property. This messes up some spke sorters otherwise
=> Do NOT return location property if nan

spikeextractors/extractors/neoextractors/neobaseextractor.py
fixes this https://github.com/SpikeInterface/spikeextractors/issues/369 the right way
=> Fixes to neo additional_gain

spikeextractors/extraction_tools.py, spikeextractors/extractors/jrcsortingextractor/__init__.py, spikeextractors/extractors/jrcsortingextractor/jrcsortingextractor.py, spikeextractors/extractors/matsortingextractor/__init__.py, spikeextractors/extractors/matsortingextractor/matsortingextractor.py
Reads pertinent data from the JRCLUST output mat file. On the way I implemented a rudimentary .mat file reader that should handle both old-style and new-style .mat files. Writing output is tricky because I'm not sure how one could write a .mat file, as opposed to an HDF5 file.
Let me know if any naming conventions are off!
=> A sorting extractor for JRCLUST output

spikeextractors/sortingextractor.py
- fixes propertu retrieval when empty sorting extractor (might happen after auto curation etc)
=> Empty unit fixes

spikeextractors/multisortingextractor.py, spikeextractors/sortingextractor.py
Added indices to multisortingextractor and sorted indices/features for convenience.
=> sorted features and indices for convenience

spikeextractors/extractorlist.py
Neuroscope was missing from the extractorlist module.
=> add neuroscope to available sorting extractors

spikeextractors/multirecordingchannelextractor.py, spikeextractors/multirecordingtimeextractor.py, spikeextractors/multisortingextractor.py, spikeextractors/tests/test_extractors.py
=> properties for multis

spikeextractors/extractors/nwbextractors/nwbextractors.py
https://github.com/SpikeInterface/spikeextractors/issues/390 
pynwb 1.2.1
@luiztauffer can you double check this?
=> Fix nwb property save/load

spikeextractors/extraction_tools.py, spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py, spikeextractors/extractors/mea1krecordingextractor/mea1krecordingextractor.py
Added different versions of the Mea1k chip in the Mea1kRecordingExtractor
=> Mea1k versions

spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeextractors/extractors/exdirextractors/exdirextractors.py, spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py, spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py, spikeextractors/extractors/klustaextractors/klustaextractors.py, spikeextractors/extractors/matsortingextractor/matsortingextractor.py, spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py, spikeextractors/extractors/mcsh5recordingextractor/mcsh5recordingextractor.py, spikeextractors/extractors/mea1krecordingextractor/mea1krecordingextractor.py, spikeextractors/extractors/mearecextractors/mearecextractors.py, spikeextractors/extractors/neoextractors/neobaseextractor.py, spikeextractors/extractors/nixioextractors/nixioextractors.py, spikeextractors/extractors/nwbextractors/nwbextractors.py, spikeextractors/extractors/openephysextractors/openephysextractors.py, spikeextractors/extractors/shybridextractors/shybridextractors.py, spikeextractors/extractors/spykingcircusextractors/spykingcircusextractors.py, spikeextractors/extractors/tridescloussortingextractor/tridescloussortingextractor.py, spikeextractors/extractors/waveclussortingextractor/waveclussortingextractor.py
Unified installation messages and assertions among extractors
=> Unified installation_msg

setup.py, spikeextractors/cacheextractors.py, spikeextractors/extraction_tools.py, spikeextractors/recordingextractor.py
It's a nice way to trak progress:
=> Use tqdm when verbose for write to binary and h5

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py, spikeextractors/extractors/nwbextractors/nwbextractors.py
Minor refactoring to `NwbRecordingExtractor.write_recording` helper functions handling of metadata. Let me know if you would like to meet to discuss, or have any questions.
=> Nwb extractor writing update

spikeextractors/extractors/nwbextractors/nwbextractors.py
- Remove unnecessary warnings when metadata only contains a subfield
- Fixed bug for features: `spikes_index = np.cumsum(nspks_list).tolist()` the `tolist()` was somewhow causin an overflow error, leading to an issue in loading back the features. Setting to int64 fixes the issue
=> Fix print warning and bug for spike_index type

spikeextractors/extractors/maxonerecordingextractor/maxonerecordingextractor.py, spikeextractors/extractors/mea1krecordingextractor/mea1krecordingextractor.py
- reinserted signal retrieval
- cleaned up Mea1k
=> Fix MaxOne

spikeextractors/extractors/mdaextractors/mdaextractors.py
https://github.com/SpikeInterface/spikeextractors/issues/454
=> Add verbose arg to MDA write_to_dat_binary

spikeextractors/extractors/nwbextractors/nwbextractors.py
Quick fix to a silly issue I should have caught a while back. Good to go pending your approval. Hopefully this is the last one needed for a little while.
=> fix for add_electrodes column names

spikeextractors/extractorlist.py, spikeextractors/extractors/combinatosortingextractor/__init__.py, spikeextractors/extractors/combinatosortingextractor/combinatosortingextractor.py
Hi Guys,
I'm still working on the interface to run Combinato, but the extractor is done, and probably you want to take a look on it.
=> adds combinatosortingextractor

spikeextractors/extractors/nwbextractors/nwbextractors.py
1. Replaced all nested if checks with single line assertion
2. Better organized initial metadata auto-population and defaults, including auto-creation of default device
3. Replaced dictionary definitions with literals
5. Enforced Numpy docstring/PEP8
=> refactor of add_electrical_series

spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py
The previous Intan version was not lazy loading the data. This is fixed by this PR which uses pyintan 0.2.0
=> Use pyintan 0.2.0 for lazy loading

spikeextractors/baseextractor.py, spikeextractors/recordingextractor.py, spikeextractors/sortingextractor.py
This allows to use parallel processing with custom extractors
=> Allow extractor module not to have a version (for custom)

spikeextractors/extractorlist.py, spikeextractors/extractors/maxoneextractors/__init__.py, spikeextractors/extractors/maxoneextractors/maxoneextractors.py, spikeextractors/extractors/maxonerecordingextractor/__init__.py, spikeextractors/extractors/mea1kextractors/__init__.py, spikeextractors/extractors/mea1kextractors/mea1kextractors.py, spikeextractors/extractors/mea1krecordingextractor/__init__.py
The spike times and amplitude information are in the Mea1k and MaxOne h5 files.
=> Implemented Mea1k and MaxOne sorting extractors

spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
- Added support for nidq files 
- Added the possibility to return `int16` or `float` traces (in uV)
- Removed `x_pitch` and `y_pitch` form arguments
- Remove unefficient `write_recording` function (the `write_to_binary_dat_format` should be used instead for `.bin` files)
=> Support nidq files and allow to return int16 or float

spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
loading .cbin files(compressed bin) which are compressed using [mtscomp ](https://github.com/int-brain-lab/mtscomp)algo
=> loading cbin files compressed using IBL's mtscomp algo

spikeextractors/extractorlist.py, spikeextractors/extractors/alfsortingextractor/__init__.py, spikeextractors/extractors/alfsortingextractor/alfsortingextractor.py
sorting extractor for reading [ALF ](https://int-brain-lab.github.io/iblenv/one_docs/one_reference.html#alf)format spike sorted files.
=> Ibl alf sortingextractor

spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py, spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
@alejoe91 nwb-conversion-tools, which relies in this quite heavily, now uses inspect.signature to parse function arguments, and it helps greatly to have assigned annotations to each argument.
=> added type checking in function initializer

spikeextractors/extraction_tools.py, spikeextractors/multirecordingchannelextractor.py, spikeextractors/recordingextractor.py, spikeextractors/subrecordingextractor.py
Fixes https://github.com/SpikeInterface/spiketoolkit/issues/411
=> Fix copy properties for Sub and Multi extractor

spikeextractors/extractors/spikeglxrecordingextractor/readSGLX.py, spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
- return memmap objects for SpikeGLX (when possible)
- remove SpikeGLX verbosity
=> Spikeglx memmap

spikeextractors/extractorlist.py, spikeextractors/extractors/neoextractors/__init__.py, spikeextractors/extractors/neoextractors/blackrockextractor.py
Tested on https://gin.g-node.org/NeuralEnsemble/ephy_testing_data
@samuelgarcia let me know if it looks good so I can merge this :)
=> Implemented Blackrock NEO extractors

spikeextractors/extractorlist.py, spikeextractors/extractors/cellexplorersortingextractor/__init__.py, spikeextractors/extractors/cellexplorersortingextractor/cellexplorersortingextractor.py, spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py, spikeextractors/tests/test_extractors.py
@bendichter Added simple sorting extractor for Cell Explorer format.
@alejoe91 Did I forget to add anything for the tests or imports?
=> Add cell explorer sorting extractor

spikeextractors/extractors/phyextractors/phyextractors.py
Fixes https://github.com/SpikeInterface/spikeextractors/issues/515
=> Remove extra dimension in amplitudes for PhySortingExtractor

setup.py, spikeextractors/extractors/biocamrecordingextractor/biocamrecordingextractor.py, spikeextractors/extractors/cellexplorersortingextractor/cellexplorersortingextractor.py, spikeextractors/extractors/npzsortingextractor/npzsortingextractor.py, spikeextractors/extractors/waveclussortingextractor/waveclussortingextractor.py
Added scipy and joblib to requirements.
=> added missing dependencies

spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py
@alejoe91 @bendichter 
Minor extension for intan extractor to include int16 dtype - dependent on [pyintan PR #10](https://github.com/alejoe91/pyintan/pull/10)
=> minor extension for intan to int16 dtype

.travis.yml, spikeextractors/baseextractor.py
@samuelgarcia @colehurwitz 
This implements `object_properties`. It comes very handy for example to store channel locations in a sorting extractor.
Let's discuss!
=> Implemented 'object_properties' in BaseExtractor

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py, spikeextractors/tests/test_extractors.py
@bendichter @alejoe91 Added an extra argument for `NeuroscopeRecordingExtractor` that specifies proper gain values.
=> NeuroscopeRecordingExtractor gains

spikeextractors/extractors/neoextractors/blackrockextractor.py, spikeextractors/extractors/neoextractors/neobaseextractor.py
a small fix on NeoBaseRecordingExtractor
=> fix reader

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py, spikeextractors/extractors/nwbextractors/nwbextractors.py
@alejoe91 As per our discussion, here is the incorporation waveform data from .spk files to the Neuroscope extractor using the current method of encoding features.
@bendichter Will likely be improved in the near future in terms of memory usage.
=> Add neuroscope waveforms

spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
Fixes https://github.com/SpikeInterface/spikeextractors/issues/559
=> Allow imec.ap and imec.lf files for spikeglx

spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py, spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py, spikeextractors/extractors/nwbextractors/nwbextractors.py
@alejoe91 Got around to updating this per our discussion
=> return_scaled - bindat, neuroscope, and intan

spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
Reported here: https://github.com/SpikeInterface/spikeextractors/issues/564
=> Fix spikeglx typo in assertion

spikeextractors/extractors/klustaextractors/klustaextractors.py, spikeextractors/extractors/neoextractors/blackrockextractor.py, spikeextractors/extractors/neoextractors/neobaseextractor.py
- fix for Klusta when spikes are not identified in specific channel groups fix #554 
- a fix for blackrock that I forgot to commit before got bundled on it... since it's a small thing, I hope that's ok? fix #543
=> Fix klusta

spikeextractors/extractors/intanrecordingextractor/intanrecordingextractor.py
Related to indexing bug for lazy access here: https://github.com/alejoe91/pyintan/pull/11
=> pyintan>=0.3.0

spikeextractors/extractors/spykingcircusextractors/spykingcircusextractors.py
@yger can you check this?
- the `SpykingCircusRecordingExtractor` can now load from NUMPY and RAW_BINARY format
- the `SpykingCircusSortingExtractor` can load a specific curated result file (using e.g. the SC GUI) and it can additionally load the templates
=> Update SC extractors

spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py
This makes the spikeGLX locations the same as the OpenEphysNPIX 'official' ones (which are the same as the ones in this issue: https://github.com/SpikeInterface/spikeextractors/issues/561).
=> Added x_offset and y_offset to match official Neuropixels locations

spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py, spikeextractors/extractors/maxwellextractors/maxwellextractors.py, spikeextractors/extractors/mdaextractors/mdaextractors.py
To avoid conflict with the `self._times` in the base extractor
=> Rename self._times --> self._spike_times in HSSorting

.github/workflows/python-publish.yml
@colehurwitz can you add me as a maintainer to the spikeextractors project on PyPI?
=> Update publish workflow

spikeextractors/example_datasets/toy_example.py
@alejoe91 Self-explanatory. I'm constructing some data interfaces that rely on this for simulating example data.
=> Add annotation to toy example

spikeextractors/extractors/nwbextractors/nwbextractors.py
fix #610 
@khl02007 Thanks for checking this. The option also requires that the data to be in a numpy memmap, which may not always be the case.
@alejoe91 Sorry I missed this in the early PR devoted to it.
=> fix issue 610

spikeextractors/extractors/cedextractors/cedrecordingextractor.py
The CEDRecordingExtractor already return scaled traces, so gains should not be set. Instead a property called `ced_gain` is set.
=> Fix gains and scaling in CED

spikeextractors/baseextractor.py, spikeextractors/cacheextractors.py, spikeextractors/extraction_tools.py, spikeextractors/multirecordingchannelextractor.py, spikeextractors/multirecordingtimeextractor.py, spikeextractors/multisortingextractor.py, spikeextractors/recordingextractor.py, spikeextractors/sortingextractor.py
This PR responds to #618, which was about some out of order arguments in docstrings. As I did a quick sweep to check for occurrences of this, I also did some suggested tweaks and fixes to the docstrings. 
Most updates are organizational / aesthetic, but note that the arguments `channel_maps` and `channel_groups` in `extraction_tools.load_probe_file` and `recordingextractor.load_probe_file` didn't previously have descriptions, so I added some based on what I could infer from the code. These probably want checking for accuracy.
=> [DOC] - Update docstrings.

spikeextractors/extractors/nwbextractors/nwbextractors.py
updated with new property descriptions for auto generated propeprties in spike detection
=> more nwb sorting default property descriptions

spikeextractors/__init__.py, spikeextractors/baseextractor.py, spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/testing.py, tests/test_extractors.py
=> Allow relative paths in dumping

spikeextractors/extractors/cedextractors/utils.py
fix for https://github.com/catalystneuro/mease-lab-to-nwb/issues/34
=> fix ced time offset

spikeextractors/extractors/cedextractors/cedrecordingextractor.py, spikeextractors/extractors/cedextractors/utils.py
Issue https://github.com/catalystneuro/mease-lab-to-nwb/issues/34
=> CED: time offset for get_num_frames

spikeextractors/extractors/cedextractors/utils.py
=> Fixes for CED

spikeextractors/__init__.py, spikeextractors/extraction_tools.py, spikeextractors/save_tools.py
@alejoe91 @luiztauffer Let me know if you'd like this moved to a particular corner of this ecosystem, or even a different repo.
=> added save_si function

spikeextractors/extractors/phyextractors/phyextractors.py
- Ensure `ch_group` property is renamed to `group`. And ensure contents are `int` (not `str` for instance).
=> cast group ids from phy to int and rename ch_group to group

.github/workflows/python-package.yml, spikeextractors/cacheextractors.py, spikeextractors/extractors/cedextractors/cedrecordingextractor.py, tests/test_extractors.py, tests/test_gin_repo.py
Fix #647 
- Set gain values as `gain` instead of `ced_gain`
- Set `self.has_unscaled = True` for decorator `@check_get_traces_args` to work
=> CED set gains

spikeextractors/extractors/neuroscopeextractors/neuroscopeextractors.py, tests/test_extractors.py
@alejoe91 Noticed a recent merge to master didn't trigger tests and as such are now failing. Investigating.
=> Fix CI tests

spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py, tests/test_gin_repo.py
Remove deprecation warnings from comparison with unequal channels.
=> Remove comparision deprecation warning
